---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ .Values.name }}
  labels:
    app.openshift.io/runtime: rh-spring-boot
  annotations:
    app.kubernetes.io/vcs-uri: {{ .Values.s2i.source.repo }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: "{{ .Values.name }}:{{ .Values.version }}"
  source:
    git:
      uri: {{ .Values.s2i.source.repo }}
      ref: {{ .Values.s2i.source.ref }}
    {{- if .Values.s2i.source.contextDir }}
    contextDir: {{ .Values.s2i.source.contextDir }}
    {{- end }}
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: "builder-{{ .Values.name }}:{{ .Values.s2i.builderImage.tag }}"
      env:
      {{- if .Values.s2i.env }}
{{ toYaml .Values.s2i.env | indent 6 }}
      {{- end }}
  triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
