---
{{- if .Values.docker }}
apiVersion: apps/v1
kind: Deployment
{{- end }}
{{- if empty .Values.docker }}
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
{{- end }}
metadata:
  labels:
    app: {{ .Values.name }}
    provider: {{ .Values.provider }}
    app.kubernetes.io/runtime: rh-spring-boot
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
{{- if .Values.docker }}
    matchLabels:
      app: {{ .Values.name }}
      provider: {{ .Values.provider }}
{{- end }}
{{- if empty .Values.docker }}
    app: {{ .Values.name }}
    provider: {{ .Values.provider }}
{{- end }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        provider: {{ .Values.provider }}
        app.kubernetes.io/runtime: rh-spring-boot
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
        {{- if .Values.env }}
{{ toYaml .Values.env | indent 12 }}
        {{- end }}
        {{- if .Values.health.enabled }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: {{ .Values.health.livenessProbe }}
              port: {{ .Values.port }}
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: {{ .Values.health.readinessProbe }}
              port: {{ .Values.port }}
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
        {{- end }}
          name: {{ .Values.name }}
        {{- if .Values.docker }}
          image: {{ .Values.docker.image }}
        {{- end }}
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
{{- if empty .Values.docker }}
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - {{ .Values.name }}
        from:
          kind: ImageStreamTag
          name: "{{ .Values.name }}:{{ .Values.version }}"
      type: ImageChange
{{- end }}