{{- if empty .Values.docker }}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: "builder-{{ .Values.name }}"
spec:
  dockerImageRepository: {{ .Values.s2i.builderImage.repo }}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Values.name }}
spec: {}
{{- end }}