{{- if .Values.route.expose }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.name }}
    provider: {{ .Values.provider }}
    app.kubernetes.io/runtime: rh-spring-boot
  name: {{ .Values.name }}
spec:
  path: /
  port:
    targetPort: {{ .Values.port }}
  to:
    kind: Service
    name: {{ .Values.name }}
{{- end }}