apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
    provider: {{ .Values.provider }}
    app.kubernetes.io/runtime: rh-spring-boot
  name: {{ .Values.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
  selector:
    app: {{ .Values.name }}
    provider: {{ .Values.provider }}
  type: ClusterIP
