apiVersion: v1
entries:
  spring-boot-example-app:
  - apiVersion: v1
    created: "2022-02-01T12:02:42.940806895Z"
    description: Spring Boot Example application
    digest: a233988522a9c39983737c372248b53345962ed17f02005b27a58d80d224d87e
    name: spring-boot-example-app
    urls:
    - charts/spring-boot-example-app-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v1
    created: "2022-02-01T10:16:51.155038287Z"
    description: Spring Boot Example application
    digest: f01e1df9eb305fbc1c0d1c01ce08879f54070909ec57b99333398e3214675c38
    name: spring-boot-example-app
    urls:
    - charts/spring-boot-example-app-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v1
    created: "2022-01-28T06:11:12.151211723Z"
    description: Spring Boot Example application
    digest: ce84140ae50b819d9fad9dea6271f91902346d13608f966afe8134aee95160aa
    name: spring-boot-example-app
    urls:
    - charts/spring-boot-example-app-0.0.1.tgz
    version: 0.0.1
generated: "2022-02-01T12:02:56Z"
serverInfo: {}
