# Application name. Example: rest-http
name: 
# Application version. Example: 2.4.9-14-SNAPSHOT
version: 
# Application provider.
provider: snowdrop
# Default port
port: 8080
# Expose route
route:
  expose: false
# Expose ingress
ingress:
  host:
# Health configuration
health:
  enabled: true
  livenessProbe: /actuator/health/liveness
  readinessProbe: /actuator/health/readiness
# docker.image configuration: If set, S2i configuration won't be used
docker:
# S2i configuration
s2i:
  # Git source repository
  source: 
    repo: 
    ref: 
  # Builder Image
  builderImage: 
    # Repository Url
    repo: registry.access.redhat.com/ubi8/openjdk-8
    # Builder Image tag
    tag: 1.3